### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [kakone/LibVLCSharp.Forms.MediaPlayerElement#1]
Congratulations on the work, I have some doubts:

Do you have to implement?
Do you have any idea what features the player will have?
Term preview?

**Comment by kakone** [comment]
Thanks,

For the first version, I want to have :
- Auto hide feature (done)
- Customizable controls (done)
- Buffering progress bar (done)
- Seek bar (done)
- Remaining time (done)
- Play/pause button (done)
- Zoom button (done)
- Stop button (done)
- Audio track / subtitles selection button (done)
- Cast button (almost finished)
- Error messages panel

The preview is already there, the code is available in this repository. I will do a NuGet package when the issues [#123](https://code.videolan.org/videolan/LibVLCSharp/issues/123) and [#124](https://code.videolan.org/videolan/LibVLCSharp/issues/124) will be fixed.

**Comment by andersonvieiragomeslopes** [comment]
Very Good, @kakone.
Is it also possible to do this? 
https://github.com/xamarin/monodroid-samples/tree/master/android-o/PictureInPicture

I look forward to the plugin to experiment, work with streaming, and videos, are limited to xamarin.forms

**Comment by kakone** [comment]
PIP mode is the next step after the first release, but I didn't look at how it works for the moment.

**Comment by andersonvieiragomeslopes** [comment]
> PIP mode is the next step after the first release, but I didn't look at how it works for the moment.

Thank your for good job.

**Comment by andersonvieiragomeslopes** [comment]
@kakone  If it is not laborious, could you send me an unofficial nuget for me to install on my project? is that the sample does not compile on my computer (slow internet time out to download the plugins), I could not test the power of this video player yet.

**Comment by andersonvieiragomeslopes** [comment]
Did you allow custom icons (play, pause, next, back, fullscreen) in the video player? @kakone

**Comment by chaosifier** [comment]
Great work! Any plans for full screen support?

**Comment by mfkl** [comment]
What do you mean by full screen support exactly?

**Comment by chaosifier** [comment]
By full screen, I mean the ability to expand the video player view across the entire screen. Like what the full screen button does while playing a video in youtube app.

**Comment by tnaznen** [comment]
@kakone Can I have the example of those new features that you have done?

**Comment by andersonvieiragomeslopes** [comment]
@chaosifier https://code.videolan.org/videolan/LibVLCSharp/tree/feature/mediaelement-initial-setup
